# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'
steps:
- script: |    
    docker run --rm -u root -v $(pwd):$(pwd) --entrypoint=$(pwd) prancer/prancer-cli:1.0.3 ls -l
  displayName: 'npm install and build'
