# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'
steps:
- script: |    
    pip install prancer-cli
  displayName: 'prepare-env'
  
- script: |    
    prancer-cli -h
  displayName: 'run-test'  
