trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'
steps:
- script: |
    sudo pip3 install prancer-cli==1.0.2    
  displayName: 'prepare-env'
  
- script: |    
    printenv
    prancerent -a create -u ${ENTCLI_KEY} -p ${ENTCLI_SECRET}
    prancerent -t default_container -o
  displayName: 'run-test'  
